travis:
  secure:
    BINSTAR_TOKEN: t7TRGShRRCW4U+3OlXAJ/ip3LIJG0G+Cb6Vxv5YyZUmM3waLYJTsE9ANuOnox+5QIR2BZqrrhwgX22mE0n8NxufMmoh43fRJy0G5xygsf6d8o6Mlh2d+/cEM+XKt2VBIT4x63GiQ4dxTDXrG7J7c/jJl1S7KfTQnXBrFVTiqDvMjeKaeXRKPSc//V3vveU+EpsYeuZIPOcnGo8aEOFE+8695YSCyTXaA8ykvg+U7EY6nXqjAiDcj/6vSw/MxaTJb6oqgEhV7TUz6n3BMTUHXX7YbyZ94sOZxzcMKM4oeaJFZZkDOOZz8snkg8cdrr50BcBv6ikTMex/T+BgH0aUkBxq18K367SuJS/tZdP4L0uJhNpBFFGr/sLjOntVBLHip9LvRTAV4gh4IQQ25qTyuPWcb5poCiPxb1Scd956J76ZzYQGq2/lRukPevFwQa1+oAV3ZsY+CSg608KlsZ4m9CkJx0rka8qusUw0o35iD5EmiJLBskrePg3cB16ngvqrsgUHBuOnnKJ7lCf5oNaFYP7EJYEiOBSZloyT9V4vfkNdUUAdNi2tc9ncLQOQc71qFxKyvQSAQTzKIHak5Y7nYqIjJRK+Ofval4fbv49H70kLbIz8NWQzpeHl1UrF6sYUhqL1PzTArTf7p6jeA/WELJStW4hVg6oa9lMBqSctxbZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
