travis:
  secure:
    BINSTAR_TOKEN: yGHfJUk3+cuEkxCZ3URKIstn1CRQKuWOETacWrmpeNcDTCA2KBMYzn5fOfPQaOt3b3XTQQEppOMJBz7NQxS0veqHdc4dTlZmruBBlv1fdfmuZN8856HwaK5aL4KxvwcITkdu1QELUty1PbcV6FJJZtdBbTGD8Rp8nuaorik0BW8QW558C4SE5EQa8ZYTaIJrz8Zl1OA4/lvT/HlwZthaLCHwracKVnaCww4gLJAhTxXNoLfylXXHRC6j/J8atapS8ljpVBNBVzU0vVAOlaDQh3/u++HspK7+lBbeLUnO9uaPKYfkgM1AWYxla7o6K0C0bvhLeZoPh6q4cFj+X+bcNIDKB74BcbzA27iSNm3Nc4N1zwbbpl6POyjcsQJGtQcdvGPYQ8M4/Byq5s+/p2rMWxUwmUBbJRJIoouvW8DlSXGbENIDcwaHJNz2K3nZu0ehq8p5S3DHJji41zm9hYbfu6mDRDdvP7ADPGZ39/gzCgkniYoGPml6UJAyiMaope5XRKK5a/E/bCD5a7IwKz+vHVZM0cR0fHAqXP4K/ZCD26EmH8Qo+/WkCMGHCwunARv7LVLpW1l9yL+6tf6n/dw3/3MJkQ5OEtB1qOvAcNU9wPk5EcHfJNoq5Qsd2EsacKBV6ipZ1qubnhKPReXXougJf+pYXaGLkG/u1n0FfJdxPyY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
