appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: XnJU97IFhfceeJVvgZYlBk8uy/mi4sOSsnb+jIgkUOtHkaYsUe1go4sjFQCfJp/v4ch72GEOSHDVuHFiBig/My5OkDrq6Hhs8dG0Cg/Kiv73mfHjvYv2n1sGrEb7NgD0l3uUBskRqIXJRIscjr+iio7x3UwxITHF56w+egExCNhFPQuHAGBQ3KrxQRJpIjSSfYEOLQG+hHQN7o8gCMEDQDielknWCJ5C48acbHWU1OZec+T8XcBs0aJAgbTSBVbWKOWS4kAg8USaEfw1VY/hOGNYuyJ/AdpEafS5PtcA/S0ZOJkgj+LczXJO08N9G7vRNGVdRscy8EVTxln28k01zXGjz8ySvqT6wVcO3C6Y9cU9zUEDqmbsT48IUbX0MTHPVUXfN/6U/t8hVCNNwaSjD0yW/xBfRVlFWZnIYhnYfhTO49RZM4cU0ArAlCvO3CEx48X94WDw68RbSuRq6JNHUAuXNehx7Vm9lofpuXHYcRJMBMsSL869/d2huvK2RR9P4NX4MKWTEiO3zaWIi6iftDYDIXUfod3+45Scd5Zn939UGyfUGqC8Dfgf4eVScWaB8XWdSLIKULSFLH0ya9mICsk8IY1ZexoGGXiQ5MGUz2JqRU6KvrZlDe2Q5J5gk4USqyTDJb7sJCa+/bodf62ypA0cd25QTNL47WKwNE50SH4=}
