travis:
  secure:
    BINSTAR_TOKEN: TAr42k3+wjm1rcFGMRmevGbY9ZeDt4lio/r0jED32+e11GAEtbiXIEMEVXkTlT27NWGwRHzLuYP6HpYKk/SyknVk4N60236NR0KgKhQTfPwo0urJD8QjbiLV7NzgqkfVr8CEUh8UVwq74ZqAAGoy16EjBmwpJ0LGTDYbTjmvQ469wl9rgI3qrRJssYv+wLhg/hZ+DqXTZ5sbJQIVSecYdZF0RLV7l1xPw+F7lyO+C6iojcWnWmko7AugEKhlCX0ZDZOK/sFt42t+HBcBcjlBEE6D8YUYxlxm1MvMYZzWjClnHn9oYsSDq88fkVsp3WbPlePdEVMFMR4npM70p294ZPk3murPi1Vvyc3czdT/lcsEj8wiFaL/gszXLU7LfaS4QrdAQonY92LpnUQwZwmfltXWarbR/UyR/edCJ/kHdj4TuKRnttyu52XvYb1rXr9ISfetrAGF1u8l1sX6auvvl6zH5eCn5eQWDBzTgDpxawzQmSFywMB9SurMSBV8GFeGANnV9oEqc4VGBujUDEbQzofS2U2gzGzC3MuiOziKzWVDpsaVf6BY6aO1JViB1eMmIajLo6Soj7NpoJB1UMuNrByUNu+V28/WgEYV72tZzfW/xRw+g8C5huiYf72e6A2oy6bXW2yI4iC9f+bi99rXNRYTLCDu43309RUmLrYdO+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
